language: swift
osx_image: xcode8.3
#xcode_project: MyNewProject.xcodeproj # path to your xcodeproj folder
xcode_workspace: KnxBasics2.xcworkspace
xcode_scheme: KnxBasics2

cache: cocoapods

before_install:
  - pod install --repo-update

script:
  - xcodebuild -workspace KnxBasics2.xcworkspace -list
  - xcodebuild -workspace KnxBasics2.xcworkspace -scheme KnxBasics2
  - xcodebuild -workspace KnxBasics2.xcworkspace -scheme KnxBasics2 test
  
